seed: 42
image_size:
batch_size: 64 # 64 takes up almost all of the 2x t4s so it is a good number
lr:
epochs: 100 # This is the max epochs, as we plan to add early stopping etc 
loss:          # you used BCE + Dice before; what name will you use to select it in code?
encoder:       # e.g. a torchvision model name
pretrained:    # true/false
num_workers:
output_dir: